name: conda-on-air  # conda env name of your project
version: "1.0.0"  # version of the conda-on-air specs
packages:
  pre-commit:
    url: https://github.com/conda-forge/pre-commit-feedstock
    rev: 0593e8a384918569be52ae290f9b9a6bb32584ea
    version: "3.3.2"
    patches:
      - original-file: recipes/meta.yaml
        patch-file: conda/on-air/patches/pre-commit/3.3.2/meta.yaml
